### ISSUE TITLE
报警和恢复的模板能分开吗？

### ISSUE THREAD

**Issue by tonglv** [lckei/prometheus-wechatbot-webhook#1]
1，报警和恢复的模板分开，这个测试了一下，没成功
2，时间可以写成这样的格式
故障时间:    {{ ($alert.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
恢复时间:    {{ ($alert.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}

**Comment by lnxyz** [comment]
reply:
1.报警和恢复是由prometheus的 alert rule决定，你不能拆分两个模板，但你可以通过模板语法采用逻辑判断语句（alert strcut中有相关参数）来实现。
2.这些语法及关键词由是 golang text/template 模板包传参决定，你上面 `Add.28800e9)` 是使用参数有问题的，你直接看模板tmpl 中 `{{ $alert.StartsAt.Format "2006-01-02 15:04:05" }}` 另外，你想使用 $alert 则需要 把模板的中 range 语句改一下就可以了，如：`{{ range .Alerts }}` --> `{{ range $i, $alert :=.Alerts }}` 就可以引用你的变量了。
想用那个参数，你可以参考源码里面定义的结构体：
```go
type Alert struct {
	Status       string    `json:"status"`
	Labels       KV        `json:"labels"`
	Annotations  KV        `json:"annotations"`
	StartsAt     time.Time `json:"startsAt"`
	EndsAt       time.Time `json:"endsAt"`
	GeneratorURL string    `json:"generatorURL"`
	Fingerprint  string    `json:"fingerprint"`
}
```

你这种逻辑判断就行，我截一个示例，你可以测试一下：

```
告警详情: {{ $alert.Annotations.summary }}
故障时间: {{ $alert.StartsAt.Format "2006-01-02 15:04:05" }}
恢复时间: {{ $alert.EndsAt.Format "2006-01-02 15:04:05" }}
===参考信息===
{{ if gt (len $alert.Labels.instance) 0 -}}故障实例ip: {{ $alert.Labels.instance }};{{- end -}}
{{- if gt (len $alert.Labels.namespace) 0 -}}故障实例所在namespace: {{ $alert.Labels.namespace }};{{- end -}}
{{- if gt (len $alert.Labels.node) 0 -}}故障物理机ip: {{ $alert.Labels.node }};{{- end -}}
{{- if gt (len $alert.Labels.pod_name) 0 -}}故障pod名称: {{ $alert.Labels.pod_name }};{{- end -}}
```
